//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JachtyV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jachty2
    {
        public int IDJacht { get; set; }
        public string Model { get; set; }
        public string Kategoria { get; set; }
        public string Silnik { get; set; }
        public Nullable<int> MaxOsob { get; set; }
        public Nullable<double> Dlugosc { get; set; }
        public Nullable<decimal> Cena { get; set; }
    }
}
