//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.AspNet.Identity;

namespace JachtyV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenie2
    {

        string _UserID = System.Web.HttpContext.Current.User.Identity.GetUserId();


        public int IDWypozyczenie { get; set; }

        public int IDJacht { get; set; }
        public string UserID { get {
                                     return _UserID;
                                    }
            set {
                _UserID = value;
            } }
        public Nullable<System.DateTime> DataOd { get; set; }
        public Nullable<System.DateTime> DataDo { get; set; }
    }
}
